# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a55bc54031e53e40bfe4214dbff524a5d3b63fbcedf1f829957827c94051057c1a0d45a4ee245230696cb388a39f551eda864099667fd34b4da498c4b35013de

test:
  secret_key_base: b5b2b6af7e17003827bd562633d9fe177ff3f1ed680abd0f42fda282ee69c2c960e8f01e084413709627a4db62baabd12d7c3606760890850baa238cf3cc0448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
